language: generic

sudo: required

install:
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update;        fi
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq mlton; fi
services:
      - docker

stages:
    - Build
    - Regression

jobs:
  include:
  - stage: Regression
    os: linux
    env: -CC=gcc    MLTON_COMPILE_ARGS="-codegen c" PART="-p part-1"
    script:
      - "docker run -i -v \"${PWD}:/RTMLton\" i386/ubuntu:xenial /bin/bash -c \"linux32 --32bit i386 /RTMLton/bin/travis-regression\""
  - os: linux
    env: -CC=gcc    MLTON_COMPILE_ARGS="-codegen c" PART="-p part-2"
    script:
      - "docker run -i -v \"${PWD}:/RTMLton\" i386/ubuntu:xenial /bin/bash -c \"linux32 --32bit i386 /RTMLton/bin/travis-regression-2\""
  - os: linux
    env: -CC=gcc    MLTON_COMPILE_ARGS="-codegen c" PART="-p part-3"
    script:
      - "docker run -i -v \"${PWD}:/RTMLton\" i386/ubuntu:xenial /bin/bash -c \"linux32 --32bit i386 /RTMLton/bin/travis-regression-3\""
  - os: linux
    env: -CC=gcc    MLTON_COMPILE_ARGS="-codegen c" PART="-p part-4"
    script:
      - "docker run -i -v \"${PWD}:/RTMLton\" i386/ubuntu:xenial /bin/bash -c \"linux32 --32bit i386 /RTMLton/bin/travis-regression-4\""
  - os: linux
    env: -CC=gcc    MLTON_COMPILE_ARGS="-codegen c" PART="-benchmark -skip-parts"
    script:
      - "docker run -i -v \"${PWD}:/RTMLton\" i386/ubuntu:xenial /bin/bash -c \"linux32 --32bit i386 /RTMLton/bin/travis-regression-bench\""
  - stage: Build
    os:   linux
    env:  CC=gcc    MLTON_COMPILE_ARGS="-codegen c" 
    script:
      - "docker run -i -v \"${PWD}:/RTMLton\" i386/ubuntu:xenial /bin/bash -c \"linux32 --32bit i386 /RTMLton/bin/travis-build\""

notifications:
  email: false
