language: generic

sudo: required

matrix:
  include:
  - os:   linux
    env:  CC=gcc    MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=true
  - os:   linux
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false
  - os: osx
    env:  CC=clang  MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update;        fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq mlton; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update;        fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mlton; fi

script:
  - ./bin/travis-ci


notifications:
  email: false
