/* MLton g816fc72-dirty (built Tue Sep  4 07:45:35 EDT 2018 on ubuntu) */
/*   created this file on Tue Sep 04 07:51:03 2018. */
/* Do not edit this file. */
/* Flag settings:  */
/*    align: 8 */
/*    atMLtons: (@MLton, --) */
/*    chunk: coalesce 4096 */
/*    closureConvertGlobalize: true */
/*    closureConvertShrink: true */
/*    codegen: c */
/*    contifyIntoMain: false */
/*    debug: true */
/*    defaultChar: char8 */
/*    defaultWideChar: widechar32 */
/*    defaultInt: int32 */
/*    defaultReal: real64 */
/*    defaultWord: word32 */
/*    diag passes: [] */
/*    drop passes: [] */
/*    elaborate allowConstant (default): false */
/*    elaborate allowConstant (enabled): true */
/*    elaborate allowFFI (default): false */
/*    elaborate allowFFI (enabled): true */
/*    elaborate allowPrim (default): false */
/*    elaborate allowPrim (enabled): true */
/*    elaborate allowOverload (default): false */
/*    elaborate allowOverload (enabled): true */
/*    elaborate allowOptBar (default): false */
/*    elaborate allowOptBar (enabled): true */
/*    elaborate allowOptSemicolon (default): false */
/*    elaborate allowOptSemicolon (enabled): true */
/*    elaborate allowLineComments (default): false */
/*    elaborate allowLineComments (enabled): true */
/*    elaborate allowDoDecls (default): false */
/*    elaborate allowDoDecls (enabled): true */
/*    elaborate allowRecPunning (default): false */
/*    elaborate allowRecPunning (enabled): true */
/*    elaborate allowOrPats (default): false */
/*    elaborate allowOrPats (enabled): true */
/*    elaborate allowExtendedLiterals (default): false */
/*    elaborate allowExtendedLiterals (enabled): true */
/*    elaborate allowSigWithtype (default): false */
/*    elaborate allowSigWithtype (enabled): true */
/*    elaborate allowRebindEquals (default): false */
/*    elaborate allowRebindEquals (enabled): true */
/*    elaborate deadCode (default): false */
/*    elaborate deadCode (enabled): true */
/*    elaborate forceUsed (default): false */
/*    elaborate forceUsed (enabled): true */
/*    elaborate ffiStr (default):  */
/*    elaborate ffiStr (enabled): true */
/*    elaborate nonexhaustiveExnMatch (default): default */
/*    elaborate nonexhaustiveExnMatch (enabled): true */
/*    elaborate nonexhaustiveMatch (default): warn */
/*    elaborate nonexhaustiveMatch (enabled): true */
/*    elaborate redundantMatch (default): warn */
/*    elaborate redundantMatch (enabled): true */
/*    elaborate resolveScope (default): strdec */
/*    elaborate resolveScope (enabled): true */
/*    elaborate sequenceNonUnit (default): ignore */
/*    elaborate sequenceNonUnit (enabled): true */
/*    elaborate valrecConstr (default): warn */
/*    elaborate valrecConstr (enabled): true */
/*    elaborate warnUnused (default): false */
/*    elaborate warnUnused (enabled): true */
/*    elaborate only: false */
/*    emit main: true */
/*    export header: None */
/*    exn history: false */
/*    generated output format: executable */
/*    gc check: Limit */
/*    gc module: Default */
/*    indentation: 3 */
/*    inlineIntoMain: true */
/*    inlineLeafA: {loops = true, repeat = true, size = Some 20} */
/*    inlineLeafB: {loops = true, repeat = true, size = Some 40} */
/*    inlineNonRec: {small = 60, product = 320} */
/*    input file: test */
/*    keep AST: false */
/*    keep CoreML: false */
/*    keep def use: true */
/*    keep dot: false */
/*    keep Machine: false */
/*    keep passes: [] */
/*    keep RSSA: false */
/*    keep SSA: false */
/*    keep SSA2: false */
/*    keep SXML: false */
/*    keep XML: false */
/*    extra_: false */
/*    lib dir: /media/psf/Home/git/cse/CSE/RTMLton/build/lib */
/*    lib target dir: /media/psf/Home/git/cse/CSE/RTMLton/build/lib/targets/self */
/*    loop passes: 1 */
/*    mark cards: true */
/*    max function size: 10000 */
/*    mlb path vars: [{var = MLTON_ROOT, path = $(LIB_MLTON_DIR)/sml}, {var = SML_LIB, path = $(LIB_MLTON_DIR)/sml}] */
/*    native commented: 0 */
/*    native live stack: false */
/*    native optimize: 1 */
/*    native move hoist: true */
/*    native copy prop: true */
/*    native copy prop cutoff: 1000 */
/*    native cutoff: 100 */
/*    native live transfer: 8 */
/*    native shuffle: true */
/*    native ieee fp: false */
/*    native split: Some 20000 */
/*    optimizationPasses: [<ssa2::default>, <ssa::default>, <sxml::default>, <xml::default>] */
/*    polyvariance: Some {hofo = true, rounds = 2, small = 30, product = 300} */
/*    prefer abs paths: false */
/*    prof passes: [] */
/*    profile: None */
/*    profile branch: false */
/*    profile C: [] */
/*    profile IL: ProfileSource */
/*    profile include/exclude: [(Seq [Star [.], Or [Seq [Seq [[$], [(], [S], [M], [L], [_], [L], [I], [B], [)]]]], Star [.]], false)] */
/*    profile raise: false */
/*    profile stack: false */
/*    profile val: false */
/*    show basis: None */
/*    show def-use: None */
/*    show types: true */
/*    target: self */
/*    target arch: AMD64 */
/*    target OS: Linux */
/*    type check: false */
/*    verbosity: Detail */
/*    warn unrecognized annotation: true */
/*    warn deprecated features: true */
/*    zone cut depth: 100 */
#define _ISOC99_SOURCE
#include <c-chunk.h>

#define ExnStackOffset 80
#define FrontierOffset 0
#define UMFrontierOffset 8
#define UMStackBottomOffset 2008
#define UMStackTopOffset 2008
#define StackBottomOffset 1960
#define StackTopOffset 32
#define CurrentFrameOffset 2008
PRIVATE extern  /*GLOBAL2*/ struct GC_state gcState;
PRIVATE extern  /*GLOBAL2*/ CPointer globalCPointer[0];
PRIVATE extern  /*GLOBAL2*/ CPointer CReturnQ;
PRIVATE extern  /*GLOBAL2*/ Int8 globalInt8[0];
PRIVATE extern  /*GLOBAL2*/ Int8 CReturnI8;
PRIVATE extern  /*GLOBAL2*/ Int16 globalInt16[0];
PRIVATE extern  /*GLOBAL2*/ Int16 CReturnI16;
PRIVATE extern  /*GLOBAL2*/ Int32 globalInt32[0];
PRIVATE extern  /*GLOBAL2*/ Int32 CReturnI32;
PRIVATE extern  /*GLOBAL2*/ Int64 globalInt64[0];
PRIVATE extern  /*GLOBAL2*/ Int64 CReturnI64;
PRIVATE extern  /*GLOBAL2*/ Objptr globalObjptr[1];
PRIVATE extern  /*GLOBAL2*/ Objptr CReturnP;
PRIVATE extern  /*GLOBAL2*/ Real32 globalReal32[0];
PRIVATE extern  /*GLOBAL2*/ Real32 CReturnR32;
PRIVATE extern  /*GLOBAL2*/ Real64 globalReal64[0];
PRIVATE extern  /*GLOBAL2*/ Real64 CReturnR64;
PRIVATE extern  /*GLOBAL2*/ Word8 globalWord8[0];
PRIVATE extern  /*GLOBAL2*/ Word8 CReturnW8;
PRIVATE extern  /*GLOBAL2*/ Word16 globalWord16[0];
PRIVATE extern  /*GLOBAL2*/ Word16 CReturnW16;
PRIVATE extern  /*GLOBAL2*/ Word32 globalWord32[1];
PRIVATE extern  /*GLOBAL2*/ Word32 CReturnW32;
PRIVATE extern  /*GLOBAL2*/ Word64 globalWord64[0];
PRIVATE extern  /*GLOBAL2*/ Word64 CReturnW64;
PRIVATE extern  /*GLOBAL2*/ Pointer globalObjptrNonRoot [0];
PRIVATE /*SCOPE*/ void GC_collect (CPointer x2, Word64 x1, Int32 x0);
PRIVATE /*SCOPE*/ Objptr UM_Object_alloc (CPointer x3, Word64 x2, Int32 x1, Word64 x0);
PRIVATE /*SCOPE*/ void MLton_bug (Objptr x0);
DeclareChunk (0);
Chunk (0)
	Word32 W32_0;
ChunkSwitch (0)
case 3:
L_9:
	Push (-8);
L_6:
	/*push*/ /*StackOffset*/ S(CPointer, 0) = 2;/*NotInCriticalSection*/
/*StackOffset2*/ S2(CPointer, 0) = 2;/*NotInCriticalSection*/
/*StackOffset2*/ S2(CPointer, 0) = 2;/*NotInCriticalSection*/
	Push (8);
	FlushFrontier();
	FlushStackTop();
	CReturnQ = /*J2*/ UM_Object_alloc (GCState, (Word64)(0x0ull), (Word32)(0x0ull), (Word64)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_7:
	Push (-8);
	Return ();
case 2:
	goto L_7;
case 4:
main_0:
	W32_0 = CPointer_lt (O(CPointer, GCState, 56), StackTop);/*NotInCriticalSection*/
	BNZ (W32_0, L_8);
	goto L_6;
L_8:
	/*push*/ /*StackOffset*/ S(CPointer, 0) = 3;/*NotInCriticalSection*/
/*StackOffset2*/ S2(CPointer, 0) = 3;/*NotInCriticalSection*/
/*StackOffset2*/ S2(CPointer, 0) = 3;/*NotInCriticalSection*/
	Push (8);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word64)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
	goto L_9;
case 1:
L_4:
	Push (-8);
L_1:
	/*push*/ /*StackOffset*/ S(CPointer, 0) = 0;/*NotInCriticalSection*/
/*StackOffset2*/ S2(CPointer, 0) = 0;/*NotInCriticalSection*/
	Push (8);
	goto main_0;
case 0:
	Push (-8);
	MLton_bug (G(Objptr, 0));
case 5:
	G(Word32, 0) = CPointer_lt (O(CPointer, GCState, 56), StackTop);/*NotInCriticalSection*/
	BNZ (G(Word32, 0), L_3);
	goto L_1;
L_3:
	/*push*/ /*StackOffset*/ S(CPointer, 0) = 1;/*NotInCriticalSection*/
/*StackOffset2*/ S2(CPointer, 0) = 1;/*NotInCriticalSection*/
	Push (8);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word64)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
	goto L_4;
EndChunk
