/* MLton g816fc72-dirty (built Tue Sep  4 07:45:35 EDT 2018 on ubuntu) */
/*   created this file on Tue Sep 04 07:51:03 2018. */
/* Do not edit this file. */
/* Flag settings:  */
/*    align: 8 */
/*    atMLtons: (@MLton, --) */
/*    chunk: coalesce 4096 */
/*    closureConvertGlobalize: true */
/*    closureConvertShrink: true */
/*    codegen: c */
/*    contifyIntoMain: false */
/*    debug: true */
/*    defaultChar: char8 */
/*    defaultWideChar: widechar32 */
/*    defaultInt: int32 */
/*    defaultReal: real64 */
/*    defaultWord: word32 */
/*    diag passes: [] */
/*    drop passes: [] */
/*    elaborate allowConstant (default): false */
/*    elaborate allowConstant (enabled): true */
/*    elaborate allowFFI (default): false */
/*    elaborate allowFFI (enabled): true */
/*    elaborate allowPrim (default): false */
/*    elaborate allowPrim (enabled): true */
/*    elaborate allowOverload (default): false */
/*    elaborate allowOverload (enabled): true */
/*    elaborate allowOptBar (default): false */
/*    elaborate allowOptBar (enabled): true */
/*    elaborate allowOptSemicolon (default): false */
/*    elaborate allowOptSemicolon (enabled): true */
/*    elaborate allowLineComments (default): false */
/*    elaborate allowLineComments (enabled): true */
/*    elaborate allowDoDecls (default): false */
/*    elaborate allowDoDecls (enabled): true */
/*    elaborate allowRecPunning (default): false */
/*    elaborate allowRecPunning (enabled): true */
/*    elaborate allowOrPats (default): false */
/*    elaborate allowOrPats (enabled): true */
/*    elaborate allowExtendedLiterals (default): false */
/*    elaborate allowExtendedLiterals (enabled): true */
/*    elaborate allowSigWithtype (default): false */
/*    elaborate allowSigWithtype (enabled): true */
/*    elaborate allowRebindEquals (default): false */
/*    elaborate allowRebindEquals (enabled): true */
/*    elaborate deadCode (default): false */
/*    elaborate deadCode (enabled): true */
/*    elaborate forceUsed (default): false */
/*    elaborate forceUsed (enabled): true */
/*    elaborate ffiStr (default):  */
/*    elaborate ffiStr (enabled): true */
/*    elaborate nonexhaustiveExnMatch (default): default */
/*    elaborate nonexhaustiveExnMatch (enabled): true */
/*    elaborate nonexhaustiveMatch (default): warn */
/*    elaborate nonexhaustiveMatch (enabled): true */
/*    elaborate redundantMatch (default): warn */
/*    elaborate redundantMatch (enabled): true */
/*    elaborate resolveScope (default): strdec */
/*    elaborate resolveScope (enabled): true */
/*    elaborate sequenceNonUnit (default): ignore */
/*    elaborate sequenceNonUnit (enabled): true */
/*    elaborate valrecConstr (default): warn */
/*    elaborate valrecConstr (enabled): true */
/*    elaborate warnUnused (default): false */
/*    elaborate warnUnused (enabled): true */
/*    elaborate only: false */
/*    emit main: true */
/*    export header: None */
/*    exn history: false */
/*    generated output format: executable */
/*    gc check: Limit */
/*    gc module: Default */
/*    indentation: 3 */
/*    inlineIntoMain: true */
/*    inlineLeafA: {loops = true, repeat = true, size = Some 20} */
/*    inlineLeafB: {loops = true, repeat = true, size = Some 40} */
/*    inlineNonRec: {small = 60, product = 320} */
/*    input file: test */
/*    keep AST: false */
/*    keep CoreML: false */
/*    keep def use: true */
/*    keep dot: false */
/*    keep Machine: false */
/*    keep passes: [] */
/*    keep RSSA: false */
/*    keep SSA: false */
/*    keep SSA2: false */
/*    keep SXML: false */
/*    keep XML: false */
/*    extra_: false */
/*    lib dir: /media/psf/Home/git/cse/CSE/RTMLton/build/lib */
/*    lib target dir: /media/psf/Home/git/cse/CSE/RTMLton/build/lib/targets/self */
/*    loop passes: 1 */
/*    mark cards: true */
/*    max function size: 10000 */
/*    mlb path vars: [{var = MLTON_ROOT, path = $(LIB_MLTON_DIR)/sml}, {var = SML_LIB, path = $(LIB_MLTON_DIR)/sml}] */
/*    native commented: 0 */
/*    native live stack: false */
/*    native optimize: 1 */
/*    native move hoist: true */
/*    native copy prop: true */
/*    native copy prop cutoff: 1000 */
/*    native cutoff: 100 */
/*    native live transfer: 8 */
/*    native shuffle: true */
/*    native ieee fp: false */
/*    native split: Some 20000 */
/*    optimizationPasses: [<ssa2::default>, <ssa::default>, <sxml::default>, <xml::default>] */
/*    polyvariance: Some {hofo = true, rounds = 2, small = 30, product = 300} */
/*    prefer abs paths: false */
/*    prof passes: [] */
/*    profile: None */
/*    profile branch: false */
/*    profile C: [] */
/*    profile IL: ProfileSource */
/*    profile include/exclude: [(Seq [Star [.], Or [Seq [Seq [[$], [(], [S], [M], [L], [_], [L], [I], [B], [)]]]], Star [.]], false)] */
/*    profile raise: false */
/*    profile stack: false */
/*    profile val: false */
/*    show basis: None */
/*    show def-use: None */
/*    show types: true */
/*    target: self */
/*    target arch: AMD64 */
/*    target OS: Linux */
/*    type check: false */
/*    verbosity: Detail */
/*    warn unrecognized annotation: true */
/*    warn deprecated features: true */
/*    zone cut depth: 100 */
#define _ISOC99_SOURCE
#include <c-main.h>

PRIVATE /*GLOBAL*/ struct GC_state gcState;
PRIVATE /*GLOBAL*/ CPointer globalCPointer[0];
PRIVATE /*GLOBAL*/ CPointer CReturnQ;
PRIVATE /*GLOBAL*/ Int8 globalInt8[0];
PRIVATE /*GLOBAL*/ Int8 CReturnI8;
PRIVATE /*GLOBAL*/ Int16 globalInt16[0];
PRIVATE /*GLOBAL*/ Int16 CReturnI16;
PRIVATE /*GLOBAL*/ Int32 globalInt32[0];
PRIVATE /*GLOBAL*/ Int32 CReturnI32;
PRIVATE /*GLOBAL*/ Int64 globalInt64[0];
PRIVATE /*GLOBAL*/ Int64 CReturnI64;
PRIVATE /*GLOBAL*/ Objptr globalObjptr[1];
PRIVATE /*GLOBAL*/ Objptr CReturnP;
PRIVATE /*GLOBAL*/ Real32 globalReal32[0];
PRIVATE /*GLOBAL*/ Real32 CReturnR32;
PRIVATE /*GLOBAL*/ Real64 globalReal64[0];
PRIVATE /*GLOBAL*/ Real64 CReturnR64;
PRIVATE /*GLOBAL*/ Word8 globalWord8[0];
PRIVATE /*GLOBAL*/ Word8 CReturnW8;
PRIVATE /*GLOBAL*/ Word16 globalWord16[0];
PRIVATE /*GLOBAL*/ Word16 CReturnW16;
PRIVATE /*GLOBAL*/ Word32 globalWord32[1];
PRIVATE /*GLOBAL*/ Word32 CReturnW32;
PRIVATE /*GLOBAL*/ Word64 globalWord64[0];
PRIVATE /*GLOBAL*/ Word64 CReturnW64;
PRIVATE /*GLOBAL*/ Pointer globalObjptrNonRoot [0];
void Copy_globalObjptrs(int f, int t) { memcpy(globalObjptr[t], globalObjptr[f], sizeof(globalObjptr[t])); }
static int saveGlobals (FILE *f) {
	SaveArray (globalCPointer, f);
	SaveArray (globalInt8, f);
	SaveArray (globalInt16, f);
	SaveArray (globalInt32, f);
	SaveArray (globalInt64, f);
	SaveArray (globalObjptr, f);
	SaveArray (globalReal32, f);
	SaveArray (globalReal64, f);
	SaveArray (globalWord8, f);
	SaveArray (globalWord16, f);
	SaveArray (globalWord32, f);
	SaveArray (globalWord64, f);
	return 0;
}
static int loadGlobals (FILE *f) {
	LoadArray (globalCPointer, f);
	LoadArray (globalInt8, f);
	LoadArray (globalInt16, f);
	LoadArray (globalInt32, f);
	LoadArray (globalInt64, f);
	LoadArray (globalObjptr, f);
	LoadArray (globalReal32, f);
	LoadArray (globalReal64, f);
	LoadArray (globalWord8, f);
	LoadArray (globalWord16, f);
	LoadArray (globalWord32, f);
	LoadArray (globalWord64, f);
	return 0;
}
BeginVectorInits
VectorInitElem (1, 0, 28, (pointer)"control shouldn\'t reach here")
EndVectorInits
static void real_Init() {
}
static uint16_t frameOffsets0[] = {0};
uint32_t frameLayouts_len = 4;
static struct GC_frameLayout frameLayouts[] = {
	{ML_FRAME, frameOffsets0, 8},
	{C_FRAME, frameOffsets0, 8},
	{C_FRAME, frameOffsets0, 8},
	{C_FRAME, frameOffsets0, 8},
};
uint32_t objectTypes_len = 7;
static struct GC_objectType objectTypes[] = {
	{ STACK_TAG, FALSE, 0, 0 },
	{ NORMAL_TAG, TRUE, 16, 1 },
	{ WEAK_TAG, FALSE, 16, 0 },
	{ ARRAY_TAG, FALSE, 1, 0 },
	{ ARRAY_TAG, FALSE, 4, 0 },
	{ ARRAY_TAG, FALSE, 2, 0 },
	{ ARRAY_TAG, FALSE, 8, 0 },
};
uint32_t sourceSeqs_len = 0;
static uint32_t* sourceSeqs[] = {
};
uint32_t frameSources_len = 0;
static GC_sourceSeqIndex frameSources[] = {
};
uint32_t sourceLabels_len = 0;
static struct GC_sourceLabel sourceLabels[] = {
};
uint32_t sourceNames_len = 0;
static char* sourceNames[] = {
};
uint32_t sources_len = 0;
static struct GC_source sources[] = {
};
uint32_t atMLtons_len = 2;
static char* atMLtons[] = {
	"@MLton",
	"--",
};
DeclareChunk (0);
PRIVATE struct cont ( *nextChunks []) () = {	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
};
MLtonMain (8, 0x33837712, 8, TRUE, PROFILE_NONE, FALSE, GC_DEFAULT, 0, 5)
int main (int argc, char* argv[]) {
return (MLton_main (argc, argv));
}
