/* Copyright (C) 1999-2007 Henry Cejtin, Matthew Fluet, Suresh
 *    Jagannathan, and Stephen Weeks.
 * Copyright (C) 1997-2000 NEC Research Institute.
 *
 * MLton is released under a BSD-style license.
 * See the file MLton-LICENSE for details.
 */

#ifndef DEBUG
#define DEBUG FALSE
#endif

//#define PROFILE_UMGC

enum {
  DEBUG_ARRAY = FALSE,
  DEBUG_ARRAY_OFFSET = TRUE,
  DEBUG_CALL_STACK = FALSE,
  DEBUG_CARD_MARKING = FALSE,
  DEBUG_CHUNK_ARRAY = TRUE,
  DEBUG_DETAILED = TRUE,
  DEBUG_DFS_MARK = FALSE,
  DEBUG_ENTER_LEAVE = FALSE,
  DEBUG_GENERATIONAL = FALSE,
  DEBUG_INT_INF = FALSE,
  DEBUG_INT_INF_DETAILED = FALSE,
  DEBUG_MARK_COMPACT = FALSE,
  DEBUG_MEM = TRUE,
  DEBUG_OBJPTR = FALSE,
  DEBUG_PROFILE = FALSE,
  DEBUG_RESIZING = FALSE,
  DEBUG_SHARE = FALSE,
  DEBUG_SIGNALS = FALSE,
  DEBUG_SIZE = FALSE,
  DEBUG_SOURCES = FALSE,
  DEBUG_STACKS = FALSE,
  DEBUG_STACK_GROW = TRUE,
  DEBUG_THREADS = FALSE,
  DEBUG_WEAK = TRUE,
  DEBUG_WORLD = FALSE,
  FORCE_GENERATIONAL = FALSE,
  FORCE_MARK_COMPACT = FALSE,
  DEBUG_OLD = FALSE,
  DEBUG_RTGC = FALSE,
  DEBUG_RTGC_MARKING = FALSE,
  DEBUG_WB = FALSE,
  DISPLAY_GC_STATS = TRUE
};

#define RED(x) "\033[1;31m"x"\033[0m"
#define YELLOW(x) "\033[1;33m"x"\033[0m"
#define GREEN(x) "\033[1;32m"x"\033[0m"
