/*
 * Simple RTEMS configuration
 */

#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER

#define CONFIGURE_UNLIMITED_OBJECTS
#define CONFIGURE_UNIFIED_WORK_AREAS

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE

#define CONFIGURE_RTEMS_POSIX_API

//#define CONFIGURE_POSIX_INIT_THREAD_TABLE

#define CONFIGURE_MAXIMUM_POSIX_THREADS 6

#define CONFIGURE_MEMORY_OVERHEAD 1

#define CONFIGURE_INIT

//#define CONFIGURE_SCHEDULER_EDF
//#define CONFIGURE_SCHEDULER_NAME rtems_build_name('U', 'E', 'D', 'F')

#include <rtems/confdefs.h>
